// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzY-EOJqCOLYVscjINqe8ScZQEsjAyT7Q',
    appId: '1:703059807999:web:53a39854eb9b767e5306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    authDomain: 'bus-tracking-project-1834c.firebaseapp.com',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    measurementId: 'G-X3VYGHH2JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZVXnDHOvVqT9cNP1N5L24ZPO-ko-xSM',
    appId: '1:703059807999:android:3b21dee0602e39485306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ6Bzo_nTFjw_-G24CBXWDvT3Iyh8pY',
    appId: '1:703059807999:ios:c38be216105b9b555306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingPassenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ6Bzo_nTFjw_-G24CBXWDvT3Iyh8pY',
    appId: '1:703059807999:ios:c38be216105b9b555306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingPassenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzY-EOJqCOLYVscjINqe8ScZQEsjAyT7Q',
    appId: '1:703059807999:web:53cc2150a045599e5306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    authDomain: 'bus-tracking-project-1834c.firebaseapp.com',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    measurementId: 'G-L7PVTS8B3N',
  );
}
