// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzY-EOJqCOLYVscjINqe8ScZQEsjAyT7Q',
    appId: '1:703059807999:web:53a39854eb9b767e5306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    authDomain: 'bus-tracking-project-1834c.firebaseapp.com',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    measurementId: 'G-X3VYGHH2JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZVXnDHOvVqT9cNP1N5L24ZPO-ko-xSM',
    appId: '1:703059807999:android:95375b0e888249345306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ6Bzo_nTFjw_-G24CBXWDvT3Iyh8pY',
    appId: '1:703059807999:ios:cee21e46511d68495306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingConductor',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEeZ6Bzo_nTFjw_-G24CBXWDvT3Iyh8pY',
    appId: '1:703059807999:ios:cee21e46511d68495306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingConductor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzY-EOJqCOLYVscjINqe8ScZQEsjAyT7Q',
    appId: '1:703059807999:web:84a058513b4ad2be5306ca',
    messagingSenderId: '703059807999',
    projectId: 'bus-tracking-project-1834c',
    authDomain: 'bus-tracking-project-1834c.firebaseapp.com',
    storageBucket: 'bus-tracking-project-1834c.firebasestorage.app',
    measurementId: 'G-QD057W2GEK',
  );

}